=== metno/fimex/share/etc/cdmGribWriterConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
  <xs:element name="cdm_gribwriter_config">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="template_file" minOccurs="0" maxOccurs="1" />
        <xs:element ref="global_attributes" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="axes" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="variables" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="template_file">
    <xs:complexType>
      <xs:attribute name="path" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="global_attributes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="g1attribute"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="g2attribute"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="g1attribute">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="g2attribute">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="axes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="vertical_axis"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="vertical_axis">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="grib1" type="gribAxis" minOccurs="0" maxOccurs="1"/>
        <xs:element name="grib2" type="gribAxis" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="standard_name"/>
      <xs:attribute name="unitCompatibleTo" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="variables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="parameter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="grib1"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="grib2"/>
      </xs:sequence>
      <xs:attribute name="level" type="xs:integer"/>
      <!-- one of standard_name or name is required, but it is not -->
      <!-- possible to express this with xsd -->
      <xs:attribute name="standard_name" use="optional" type="xs:string"/>
      <xs:attribute name="name" use="optional" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="gribAxis">
      <xs:attribute name="id" type="xs:integer"/>
      <xs:attribute name="add_offset" type="xs:integer"/>
      <xs:attribute name="scale_factor" type="xs:double"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="value" type="xs:double"/>
      <xs:attribute name="units"/>
  </xs:complexType>
  <xs:element name="grib1">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="attribute"/>
      </xs:sequence>
      <xs:attribute name="codeTable" type="xs:integer"/>
      <xs:attribute name="parameterNumber" type="xs:integer"/>
      <xs:attribute name="units"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="grib2">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="attribute"/>
      </xs:sequence>
      <xs:attribute name="discipline" type="xs:integer"/>
      <xs:attribute name="parameterCategory" type="xs:integer"/>
      <xs:attribute name="parameterNumber" type="xs:integer"/>
      <xs:attribute name="units"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== metno/fimex/test/grib/inputNoLonLat/cdmGribWriterConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<cdm_gribwriter_config
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<!--                        xsi:noNamespaceSchemaLocation="cdmGribWriterConfig.xsd"> -->
<!-- isotopes are an extension from CMA, stored in grib1-PDS byte 46+47 -->
<!-- it needs the isotopeIdentificationNumber extension in /usr/share/grib_api/definitions/grib1/local.54.def -->
<!-- (or a comparable file in GRIB_DEFINITION_PATH):
# applicationIdentifier     41
# type                      42
# identificationNumber      43
# productIdentifier         44
# spatialSmoothingOfProduct 45
# isotopeIdentificationNumber 46-47               2

unsigned[1] applicationIdentifier : dump ;

unsigned[1] type : dump;

unsigned[1] identificationNumber : dump;

unsigned[1] productIdentifier : dump ;

unsigned[1] spatialSmoothingOfProduct : dump  ;

#

unsigned[2] isotopeIdentificationNumber : dump ;
-->
<!-- <template_file name="template_conc_Am-241.ID_328.grib" /> -->
<template_file name="template_conc_Am-241.ID_328.grib" />
<processing_options>
    <!-- omitEmptyFields should be false except for TOA -->
    <omitEmptyFields>0</omitEmptyFields>
</processing_options>

<global_attributes>
    <!-- type can be double, long, string -->
    <attribute name="identificationOfOriginatingGeneratingCentre" value="54" type="long" />
    <attribute name="packingType" value="grid_simple" type="string" /> <!-- grid_simple, grid_second_order -->
</global_attributes>
<axes>
<!-- no vertical axis -->
<vertical_axis standard_name="">
   <!-- using height in meter, 0 -->
   <grib1 id="105" value="0" type="short"/>
   <grib2 id="103" value="0" type="short"/>
</vertical_axis>
<vertical_axis unitCompatibleTo="m">
   <!-- no standard_name for height/depth, defined only by positive=up/down -->
   <grib1 id="105" units="m" type="short"/>
   <grib2 id="103" units="m" type="double"/>
</vertical_axis>
<vertical_axis unitCompatibleTo="Pa">
   <!-- no standard_name for pressure coord, defined only by unit of hPa -->
   <grib1 id="100" units="hPa" type="short"/>
   <grib2 id="100" units="Pa" type="double"/>
</vertical_axis>
<vertical_axis standard_name="air_pressure">
   <grib1 id="100" units="hPa" type="short"/>
   <grib2 id="100" units="Pa" type="double"/>
</vertical_axis>
<vertical_axis standard_name="atmosphere_sigma_coordinate">
    <grib1 id="107" scale_factor="1e-4" add_offset="0" type="short" />
    <grib2 id="104" type="double" />
</vertical_axis>
</axes>
<variables>
<!-- translation section for parameter names/standard_names -->

<!-- time of arrival, should be in files ending with _tofa -->
<!-- time of arrival, should be in files ending with _tofa; isotope 392 = all/total -->
<parameter name="time_of_arrival">
    <grib1 parameterNumber="206" codeTable="133" units="seconds">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="392" />
    </grib1>
</parameter>


<!-- wet deposition (wdep), should be in files ending with _prec -->
<parameter name="lwe_precipitation_rate">
    <grib1 parameterNumber="203" codeTable="133" units="mm/hr"/> <!-- must be rate!!! -->
</parameter>

<!-- isotopes filled in from isotopes_template.xml -->
<!-- surface-concentrations should end in _conc files -->
<parameter name="I131_concentration">
    <grib1 parameterNumber="200" codeTable="133" units="Bq/m3">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="148" />
    </grib1>
</parameter>
<!-- column-concentrations should end in _coco files -->
<parameter name="I131_column_concentration">
    <grib1 parameterNumber="207" codeTable="133" units="Bq*m/m3">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="148" />
    </grib1>
</parameter>
<!-- dose/time-integrated concentration, should end in files named _dose -->
<parameter name="I131_acc_concentration">
    <grib1 parameterNumber="202" codeTable="133" units="Bq*h/m3">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="148" />
    </grib1>
</parameter>
<!-- total deposition (tdep), should be in files ending with _depo -->
<parameter name="I131_acc_total_deposition">
    <grib1 parameterNumber="201" codeTable="133" units="Bq/m2">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="148" />
    </grib1>
</parameter>
<!-- wet deposition (wdep), should be in files ending with _wdep -->
<parameter name="I131_acc_wet_deposition">
    <grib1 parameterNumber="205" codeTable="133" units="Bq/m2">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="148" />
    </grib1>
</parameter>
<!-- surface-concentrations should end in _conc files -->
<parameter name="Xe133_concentration">
    <grib1 parameterNumber="200" codeTable="133" units="Bq/m3">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="158" />
    </grib1>
</parameter>
<!-- column-concentrations should end in _coco files -->
<parameter name="Xe133_column_concentration">
    <grib1 parameterNumber="207" codeTable="133" units="Bq*m/m3">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="158" />
    </grib1>
</parameter>
<!-- dose/time-integrated concentration, should end in files named _dose -->
<parameter name="Xe133_acc_concentration">
    <grib1 parameterNumber="202" codeTable="133" units="Bq*h/m3">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="158" />
    </grib1>
</parameter>
<!-- total deposition (tdep), should be in files ending with _depo -->
<parameter name="Xe133_acc_total_deposition">
    <grib1 parameterNumber="201" codeTable="133" units="Bq/m2">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="158" />
    </grib1>
</parameter>
<!-- wet deposition (wdep), should be in files ending with _wdep -->
<parameter name="Xe133_acc_wet_deposition">
    <grib1 parameterNumber="205" codeTable="133" units="Bq/m2">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="158" />
    </grib1>
</parameter>
<!-- surface-concentrations should end in _conc files -->
<parameter name="Cs137_concentration">
    <grib1 parameterNumber="200" codeTable="133" units="Bq/m3">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="169" />
    </grib1>
</parameter>
<!-- column-concentrations should end in _coco files -->
<parameter name="Cs137_column_concentration">
    <grib1 parameterNumber="207" codeTable="133" units="Bq*m/m3">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="169" />
    </grib1>
</parameter>
<!-- dose/time-integrated concentration, should end in files named _dose -->
<parameter name="Cs137_acc_concentration">
    <grib1 parameterNumber="202" codeTable="133" units="Bq*h/m3">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="169" />
    </grib1>
</parameter>
<!-- total deposition (tdep), should be in files ending with _depo -->
<parameter name="Cs137_acc_total_deposition">
    <grib1 parameterNumber="201" codeTable="133" units="Bq/m2">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="169" />
    </grib1>
</parameter>
<!-- wet deposition (wdep), should be in files ending with _wdep -->
<parameter name="Cs137_acc_wet_deposition">
    <grib1 parameterNumber="205" codeTable="133" units="Bq/m2">
        <!-- see isotope_list.txt file -->
        <attribute name="isotopeIdentificationNumber" type="long" value="169" />
    </grib1>
</parameter>




</variables>
</cdm_gribwriter_config>
